### ISSUE TITLE
No effect on stash cost or unique drops

### ISSUE THREAD

**Issue by danboo** [Zypre/WolcenMods#1]
I tried your most recent 'No Stash Cost Many Uniques 2.0.zip' but it doesn't have any effect on the game. Stash tabs still cost money, no change in unique drop rates. Is it possible there is some step missing from the instructions? Here is a screenshot showing the new Umbra.pak.

My install steps were:

 - download game
 - download 'No Stash Cost Many Uniques 2.0.zip'
 - install Umbra.pak
 - start game
 - create new level 1 character
 - play through act 1 until you get to town
 - along the way, white-glowing treasures only dropped white items
 - in town the stash tabs still cost money

Thanks!

![image](https://user-images.githubusercontent.com/82860/73582668-a083b700-443a-11ea-882a-b9d230b8f785.png)

**Comment by Zypre** [comment]
I'm not really sure to be honest with you. I just downloaded the file from here and ran through. It works fine for me. Your installation also looks very correct.

The tutorial corpses drop nothing, so that can be explained, but not sure about the rest. Maybe try continuing in the story would work, but not sure why the tabs cost...
The vendor should also only sell legendaries.

**Comment by danboo** [comment]
I logged back in and checked the vendor, Mohabi, and he had typical items for a level 2. I'll try again later on another computer with a level 20 offline character and try some chests. No big deal either way, just trying to tide myself over until release. Let me know if something else comes to mind. Thanks!

**Comment by danboo** [comment]
Just wanted to mention that it did work when I tried it again later on a computer with an existing level 20 character.

Would it be hard to modify it so it drops a mix of legendary and unique items instead of all uniques? Seems like the uniques don't really scale up with levels much, nor do vendor items. It would be nice to work towards a set of high level legendaries in Champ mode.

Thanks again!
